# Imports

In [107]:
import pandas as pd
import h5py
import numpy as np
import tensorflow as tf
import h5py
import os

In [8]:
#Lanzar desde la carpeta LightX3ECGPrivate
import sys
sys.path.append('./automatic-ecg-diagnosis/')
# sys.path.append('./source/')
import predict

AttributeError: module 'tensorflow.compat.v2' has no attribute '__internal__'

# Commands

In [2]:
!git clone https://github.com/antonior92/automatic-ecg-diagnosis.git

Cloning into 'automatic-ecg-diagnosis'...


In [7]:
#Comando windows
!py -m pip install tensorflow

^C


Defaulting to user installation because normal site-packages is not writeable


In [100]:
!cd

e:\automatic-ecg-diagnosis-private\automatic-ecg-diagnosis


In [2]:
%cd automatic-ecg-diagnosis

e:\automatic-ecg-diagnosis-private\automatic-ecg-diagnosis


In [1]:
!ls

"ls" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [11]:
!wget https://www.dropbox.com/s/p3vd3plcbu9sf1o/data.zip?dl=0 -O data.zip

--2023-05-02 18:21:58--  https://www.dropbox.com/s/p3vd3plcbu9sf1o/data.zip?dl=0
Resolviendo www.dropbox.com (www.dropbox.com)... 162.125.68.18, 2620:100:6024:18::a27d:4412
Conectando con www.dropbox.com (www.dropbox.com)[162.125.68.18]:443... conectado.
Petición HTTP enviada, esperando respuesta... 302 Found
Localización: /s/raw/p3vd3plcbu9sf1o/data.zip [siguiendo]
--2023-05-02 18:21:58--  https://www.dropbox.com/s/raw/p3vd3plcbu9sf1o/data.zip
Reutilizando la conexión con www.dropbox.com:443.
Petición HTTP enviada, esperando respuesta... 302 Found
Localización: https://uc776bd503b4554baf42e8e1444b.dl.dropboxusercontent.com/cd/0/inline/B7Qub56Dm4nFxk8XRoEMlBkzsCI3PaHncyWZKodICaR55uM9eMuYuoUZnH-9USPaOcJJ6qJM3mylVU6u86B3BR2k6jWUil7g29fotfKh0d6Kir86bKWE2Qd4ddmw2mvBrzpm5X-3y240SOomVSv8E0sCPCoBATC3cVbe2ZJF0MvPxg/file# [siguiendo]
--2023-05-02 18:21:59--  https://uc776bd503b4554baf42e8e1444b.dl.dropboxusercontent.com/cd/0/inline/B7Qub56Dm4nFxk8XRoEMlBkzsCI3PaHncyWZKodICaR55uM9eMuYuoUZnH-9USP

In [12]:
!unzip data.zip

Archive:  data.zip
  inflating: data/ecg_tracings.hdf5  
replace data/README.md? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C


In [8]:
!pip3 show tensorflow

Name: tensorflow
Version: 1.14.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/tfg_luis_2223/.local/lib/python3.7/site-packages
Requires: google-pasta, astor, gast, keras-preprocessing, six, protobuf, wheel, keras-applications, absl-py, tensorboard, wrapt, grpcio, numpy, termcolor, tensorflow-estimator
Required-by: 


In [5]:
!python install -U pip

python: can't open file 'install': [Errno 2] No such file or directory


In [7]:
!python -v

# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib/python2.7/site.pyc matches /usr/lib/python2.7/site.py
import site # precompiled from /usr/lib/python2.7/site.pyc
# /usr/lib/python2.7/os.pyc matches /usr/lib/python2.7/os.py
import os # precompiled from /usr/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib/python2.7/posixpath.pyc matches /usr/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib/python2.7/posixpath.pyc
# /usr/lib/python2.7/stat.pyc matches /usr/lib/python2.7/stat.py
import stat # precompiled from /usr/lib/python2.7/stat.pyc
# /usr/lib/python2.7/genericpath.pyc matches /usr/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib/python2.7/genericpath.pyc
# /usr/lib/python2.7/warnings.pyc matches /usr/lib/python2.7/warnings.py
import warnings # precompiled from /usr/lib/python2.7/warnings.pyc
# /usr/lib/python2.7/linecache.pyc matches /usr/lib/python2.7/linecache.

In [6]:
!pip3 install tensorflow==2.2

  Could not find a version that satisfies the requirement tensorflow==2.2 (from versions: 1.13.1, 1.13.2, 1.14.0)
No matching distribution found for tensorflow==2.2


# Code

## crear hdf5

In [160]:
filename = 'data/datos.hdf5'
f = h5py.File(filename, 'w')

In [161]:
folder_path = 'CasosNumpy'
df = pd.read_csv("data/annotations/train.csv")
group_name = 'tracings'
shape = (len(df['id'].values),4096,12)
dset = f.create_dataset(group_name,shape=shape)

count = 0
for file_name in os.listdir(folder_path):
    if(file_name[:5] in df['id'].values):
        if file_name.endswith('.npy'):
            # Cargar el archivo numpy
            arr = np.load(os.path.join(folder_path, file_name))[:,:4096]
            if arr.shape != (12, 4096):
                new_arr = np.zeros((12, 4096))
                new_arr[:arr.shape[0], :arr.shape[1]] = arr
                arr = new_arr
            #arr = tf.convert_to_tensor(arr, dtype=tf.float32)
            dset[count, :, :] = arr.transpose()
            count+=1
            
# Guardar el arreglo numpy en el grupo

In [162]:
f.close()

## Modificar val.csv a como lo tiene antonio

In [9]:
df = pd.read_csv("data/annotations/train.csv")
df = df.drop(['id','age','sex','r_count','length'],axis=1)
df.to_csv("data/annotations/train_CPSC.csv")

## Otros

In [154]:
args= "data/datos.hdf5"
with h5py.File(args, "r") as f:
    x = np.array(f['tracings'])

np.size(x[1])
x.shape

(5501, 12, 4096)

# Train

In [163]:
!py train.py ./data/datos.hdf5 ./data/annotations/train_CPSC.csv

######################################
[[   0    0    1 ...    0    0    0]
 [   1    0    1 ...    0    0    0]
 [   2    0    0 ...    0    0    0]
 ...
 [5498    0    0 ...    0    0    1]
 [5499    0    0 ...    1    0    0]
 [5500    0    1 ...    0    1    0]]
<HDF5 dataset "tracings": shape (5501, 4096, 12), type "<f4">
###############init###################
######################################
[[   0    0    1 ...    0    0    0]
 [   1    0    1 ...    0    0    0]
 [   2    0    0 ...    0    0    0]
 ...
 [5498    0    0 ...    0    0    1]
 [5499    0    0 ...    1    0    0]
 [5500    0    1 ...    0    1    0]]
<HDF5 dataset "tracings": shape (5501, 4096, 12), type "<f4">
###############init###################
Epoch 1/70

85/85 [==============================] - 336s 4s/step - loss: -33834.9766 - val_loss: -147586.5312 - lr: 0.0010
Epoch 2/70

85/85 [==============================] - 330s 4s/step - loss: -105226.8594 - val_loss: -327566.4688 - lr: 0.0010
Epoch 3/70

85/

2023-05-03 13:11:27.212487: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


# Predict

In [3]:
PFOLDER="./dnn_predicts"
MFOLDER="./model"
DFOLDER="../data" #Nos hemos cambiado al directorio de automatic-ecg-diagnosis

!python predict.py $DFOLDER/ecg_tracings.hdf5 $MFOLDER/model.hdf5 --output_file $PFOLDER/model_mad.npy

Traceback (most recent call last):
  File "predict.py", line 5, in <module>
    from tensorflow.keras.models import load_model
ImportError: No module named tensorflow.keras.models


In [7]:
!python predict.py -h

Traceback (most recent call last):
  File "predict.py", line 5, in <module>
    from tensorflow import keras
ImportError: No module named tensorflow
